### ISSUE TITLE
Intake mechanism

### ISSUE THREAD

**Issue by b-cho** [RoboticsTeam4904/2022-Code#2]
**Intake mechanism**
A retractable bar containing mecanum and compliant wheels controlled by a motor. Intakes the game balls *underneath* the bar.
*Update 2021-01-30*: Need to add second motor for secondary intake
- [ ] completed

**Todo:**
- [x] Confirm final design schematic with design subteam
- [x] Assign programming members to development
  - Members: *Adam, Ethan, Rohan, Howard, Luka*
  - [x] Map out subsystem components on whiteboard
  - [x] Implement relevant subsystem files
  - [x] Add commands to *commands* folder
  - [x] Ensure components are constructed in *RobotMap.java*
- [ ] Initial implementation in branch
- [ ] Review changes and merge into 2022-Code/main
